version: '3'
services:
  engage-infra-service:
    image: 434227579614.dkr.ecr.eu-west-1.amazonaws.com/gimmetime
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: engage-infra-grp
        awslogs-region: eu-west-1
        awslogs-stream-prefix: infra
